name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go directory
      uses: actions/checkout@v2
      with:
        ref: v1.x
    - name: Build
      run: |
        export GO111MODULE=on
        export PATH=$PATH:$(go env GOPATH)/bin   
        GOOS=linux GOARCH=amd64 go build -o bin/nantoari-linux-amd64 cmd/nantoari/main.go
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: binaries
        path: bin/
